### ISSUE TITLE
Instance Redis on Windows

### ISSUE THREAD

**Issue by nickkkkkkkkkkkkkkkkkk** [EliaTolin/paapi_amazon_webserver#1]
good evening, but how do I create a Redis instance on a Windows computer? Can you do the procedure? thank you.

**Comment by EliaTolin** [comment]
Good Morning @nickkkkkkkkkkkkkkkkkk ,

[Redis is not officially supported on Windows.](https://redis.io/docs/getting-started/installation/install-redis-on-windows/)

You can use [Docker on Windows](https://docs.docker.com/desktop/install/windows-install/).

After you create a new image with Redis.
`docker run -d -p 6379:6379 --name myredis redis`

Else you can use the WSL, follow the official redis's [documentation ](https://redis.io/docs/getting-started/installation/install-redis-on-windows/)about it.
