### ISSUE TITLE
http://localhost:5000/search_product not found

### ISSUE THREAD

**Issue by hardcore** [EliaTolin/paapi_amazon_webserver#3]
Hi,

I've started the docker container with docker compose and http://localhost:5000/ works fine but neither http://localhost:5000/search_product nor http://localhost:5000/get_category_offers.

So how to create API calls? Please help :)

Thanks a lot for your work!

**Comment by EliaTolin** [comment]
Hello,
Thanks for you issue.
The correct path is this:

http://127.0.0.1:5000/api/v1/pa_amazon/search_product

I add the the prefix in the readme.

**Comment by hardcore** [comment]
Thanks a lot! :-)

I hope you can give me a little support. I want to get a JSON response from amazon pa api over HTTP request. How can I do this with for example an ASIN?

If I use "http://127.0.0.1:5000/api/v1/pa_amazon/search_product" I get an error code 405.

`127.0.0.1 - - [02/Dec/2022 10:31:30] "GET /api/v1/pa_amazon/search_product HTTP/1.1" 405 -
`
Here is my request:

```
➜ curl -X GET http://127.0.0.1:5000/api/v1/pa_amazon/search_product
<!doctype html>
<html lang=en>
<title>405 Method Not Allowed</title>
<h1>Method Not Allowed</h1>
<p>The method is not allowed for the requested URL.</p>
```


Thanks a lot!

**Comment by EliaTolin** [comment]
Hello,
I help you.

You forget the parameters for this request. [Check here the parameters](https://github.com/EliaTolin/paapi_amazon_webserver/blob/9704e803ff1d3f1621618d1b9ebf954871b987e3/routes/amazon_routes.py#L81)

I understand that the documentation in readme is not clear.
I alone to create this webserver.

But i would like it help other developers to make new app.

You are welcome.
